import prop1 from "./public/images/adambakkamProperty.jpeg";
import prop2 from "./public/images/abiramiTheatreMainRoadCommercial1.jpeg";
import prop3 from "./public/images/abiramiThaetreMainRoadcommercial2.jpeg";
import prop4 from "./public/images/thoraipakkamProperty.jpeg";
import prop5 from "./public/images/PropertyImages/5BHKVillaAtThiruvanmiyur.jpeg";
import prop6 from "./public/images/PropertyImages/Individual House at Velacherry.jpeg";
import prop7 from "./public/images/PropertyImages/OperaTulipAtPerungudi.jpeg";
import prop8 from "./public/images/PropertyImages/OperaTulipAtPerungudi.jpeg";

const propertyFullLists = [
  {
    propertyId: "DraviInfra-property1",
    propertyPrice: "2.75 crores",
    bhk: "4",
    bath: "NA",
    carParking: "NA",
    propertyName: "Individual House",
    propertyLocation: "Adambakkam, Chennai",
    prop1: prop1,
    propertyArea: "2600",
    propertyDescription: "Residential Individual Property Sale in Adambakkam.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    otherDetails: ["", ""],
    city: "NA",
    State: "NA",
  },
  {
    propertyId: "DraviInfra-property2",
    propertyPrice: "7 crores",
    bhk: "NA",
    bath: "NA",
    carParking: "NA",
    propertyName: "Commercial Building",
    propertyLocation: "Abirami Theatre Main Road, Chennai",
    prop1: prop2,
    propertyArea: "5500",
    propertyDescription:
      "For sale it is nearly 5500 sq. ft. of land and building with good rentals values. The Property is in prime area Abirami Theatre Main Road. Price 7 Crores.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    city: "NA",
    State: "NA",
  },
  {
    propertyId: "DraviInfra-property3",
    propertyPrice: "Call us for Price",
    bhk: "NA",
    bath: "NA",
    carParking: "NA",
    propertyName: "Commercial Building",
    propertyLocation: "Abirami Theatre Main Road, Chennai",
    prop1: prop3,
    propertyArea: "5500",
    propertyDescription:
      "It has super built up area of 5500 sq. ft. Now vacant. Building approved. Land area 3600 sq. ft.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    city: "NA",
    State: "NA",
  },
  {
    propertyId: "DraviInfra-property4",
    propertyPrice: "4 Crores",
    bhk: "11",
    bath: "11+",
    carParking: "4",
    propertyName: "Happy Homes",
    propertyLocation: "Thoraipakkam",
    prop1: prop4,
    propertyArea: "5200",
    propertyDescription:
      "It has super built up area of 5200 sq. ft. Land area 2200 sq. ft. Both Building and Land Approved.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    city: "NA",
    State: "NA",
  },
  {
    propertyId: "DraviInfra-property5",
    propertyPrice: "6 Crores",
    bhk: "5",
    bath: "5+",
    carParking: "-",
    propertyName: "5BHK Villa at Thiruvanmiyur",
    propertyLocation: "Thiruvanmiyur",
    prop1: prop5,
    propertyArea: "4800",
    propertyDescription:
      "It has super built up area of 4800 sq.ft. + 2400 sq.ft. Office Space with shed on Second Floor, Land area 3341 sq.ft. CMDA Approved. West Facing House with 5BHK, TV Room and Glass Room. 15 years old building.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    city: "Chennai",
    State: "Tamil Nadu",
  },
  {
    propertyId: "DraviInfra-property6",
    propertyPrice: "3 Crores",
    bhk: "-",
    bath: "-",
    carParking: "-",
    propertyName: "Individual House at Velacherry",
    propertyLocation: "Velacherry",
    prop1: prop6,
    propertyArea: "2400",
    propertyDescription:
      "It has land area of 2400 sq.ft. with building. 9 years old building. EB Connection, Water Connection and Patta Available. 30 feet road.",
    furnished: "NA",
    swimmingPool: "NA",
    gym: "NA",
    gatedCommunity: "NA",
    playArea: "NA",
    CCTVCamera: "NA",
    trashRemoval: "NA",
    city: "Chennai",
    State: "Tamil Nadu",
  },
  {
    propertyId: "DraviInfra-property7",
    propertyPrice: "1.06 Crores",
    bhk: "3",
    bath: "3",
    carParking: "2",
    propertyName: "Opera Tulip 3BHK Apartment",
    propertyLocation: "Perungudi",
    prop1: prop7,
    propertyArea: "1232",
    propertyDescription:
      "Permium 3BHK Apartment at Perungudi. 2 Units Available. It has built up area of 1232 sq.ft. and UDS of 671 sq.ft. Contact us for more details.",
    furnished: "No",
    swimmingPool: "No",
    gym: "No",
    gatedCommunity: "Yes",
    playArea: "No",
    CCTVCamera: "Yes",
    trashRemoval: "No",
    city: "Chennai",
    State: "Tamil Nadu",
  },
  {
    propertyId: "DraviInfra-property8",
    propertyPrice: "53 Lakhs",
    bhk: "1",
    bath: "1",
    carParking: "1 (if available)",
    propertyName: "Opera Tulip 1BHK Apartment",
    propertyLocation: "Perungudi",
    prop1: prop7,
    propertyArea: "616",
    propertyDescription:
      "Permium 1BHK Apartment at Perungudi. 2 Units available. It has built up area of 616 sq.ft. and UDS of 336 sq.ft. Contact us for more details.",
    furnished: "No",
    swimmingPool: "No",
    gym: "No",
    gatedCommunity: "Yes",
    playArea: "No",
    CCTVCamera: "Yes",
    trashRemoval: "No",
    city: "Chennai",
    State: "Tamil Nadu",
  },
];

export default propertyFullLists;
